# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marta/Dropbox/msc/cpp/OrbitDetermination

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marta/Dropbox/msc/cpp/OrbitDetermination

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marta/Dropbox/msc/cpp/OrbitDetermination/CMakeFiles /home/marta/Dropbox/msc/cpp/OrbitDetermination/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marta/Dropbox/msc/cpp/OrbitDetermination/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AdamsIntegration

# Build rule for target.
AdamsIntegration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AdamsIntegration
.PHONY : AdamsIntegration

# fast build rule for target.
AdamsIntegration/fast:
	$(MAKE) -f CMakeFiles/AdamsIntegration.dir/build.make CMakeFiles/AdamsIntegration.dir/build
.PHONY : AdamsIntegration/fast

#=============================================================================
# Target rules for targets named GJIntegration

# Build rule for target.
GJIntegration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GJIntegration
.PHONY : GJIntegration

# fast build rule for target.
GJIntegration/fast:
	$(MAKE) -f CMakeFiles/GJIntegration.dir/build.make CMakeFiles/GJIntegration.dir/build
.PHONY : GJIntegration/fast

#=============================================================================
# Target rules for targets named NGA

# Build rule for target.
NGA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NGA
.PHONY : NGA

# fast build rule for target.
NGA/fast:
	$(MAKE) -f CMakeFiles/NGA.dir/build.make CMakeFiles/NGA.dir/build
.PHONY : NGA/fast

#=============================================================================
# Target rules for targets named Tests

# Build rule for target.
Tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tests
.PHONY : Tests

# fast build rule for target.
Tests/fast:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/build
.PHONY : Tests/fast

#=============================================================================
# Target rules for targets named TestsMatrix

# Build rule for target.
TestsMatrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestsMatrix
.PHONY : TestsMatrix

# fast build rule for target.
TestsMatrix/fast:
	$(MAKE) -f CMakeFiles/TestsMatrix.dir/build.make CMakeFiles/TestsMatrix.dir/build
.PHONY : TestsMatrix/fast

TestAdams.o: TestAdams.cpp.o
.PHONY : TestAdams.o

# target to build an object file
TestAdams.cpp.o:
	$(MAKE) -f CMakeFiles/AdamsIntegration.dir/build.make CMakeFiles/AdamsIntegration.dir/TestAdams.cpp.o
.PHONY : TestAdams.cpp.o

TestAdams.i: TestAdams.cpp.i
.PHONY : TestAdams.i

# target to preprocess a source file
TestAdams.cpp.i:
	$(MAKE) -f CMakeFiles/AdamsIntegration.dir/build.make CMakeFiles/AdamsIntegration.dir/TestAdams.cpp.i
.PHONY : TestAdams.cpp.i

TestAdams.s: TestAdams.cpp.s
.PHONY : TestAdams.s

# target to generate assembly for a file
TestAdams.cpp.s:
	$(MAKE) -f CMakeFiles/AdamsIntegration.dir/build.make CMakeFiles/AdamsIntegration.dir/TestAdams.cpp.s
.PHONY : TestAdams.cpp.s

TestGJIntegrators.o: TestGJIntegrators.cpp.o
.PHONY : TestGJIntegrators.o

# target to build an object file
TestGJIntegrators.cpp.o:
	$(MAKE) -f CMakeFiles/GJIntegration.dir/build.make CMakeFiles/GJIntegration.dir/TestGJIntegrators.cpp.o
.PHONY : TestGJIntegrators.cpp.o

TestGJIntegrators.i: TestGJIntegrators.cpp.i
.PHONY : TestGJIntegrators.i

# target to preprocess a source file
TestGJIntegrators.cpp.i:
	$(MAKE) -f CMakeFiles/GJIntegration.dir/build.make CMakeFiles/GJIntegration.dir/TestGJIntegrators.cpp.i
.PHONY : TestGJIntegrators.cpp.i

TestGJIntegrators.s: TestGJIntegrators.cpp.s
.PHONY : TestGJIntegrators.s

# target to generate assembly for a file
TestGJIntegrators.cpp.s:
	$(MAKE) -f CMakeFiles/GJIntegration.dir/build.make CMakeFiles/GJIntegration.dir/TestGJIntegrators.cpp.s
.PHONY : TestGJIntegrators.cpp.s

readNGA.o: readNGA.cpp.o
.PHONY : readNGA.o

# target to build an object file
readNGA.cpp.o:
	$(MAKE) -f CMakeFiles/NGA.dir/build.make CMakeFiles/NGA.dir/readNGA.cpp.o
.PHONY : readNGA.cpp.o

readNGA.i: readNGA.cpp.i
.PHONY : readNGA.i

# target to preprocess a source file
readNGA.cpp.i:
	$(MAKE) -f CMakeFiles/NGA.dir/build.make CMakeFiles/NGA.dir/readNGA.cpp.i
.PHONY : readNGA.cpp.i

readNGA.s: readNGA.cpp.s
.PHONY : readNGA.s

# target to generate assembly for a file
readNGA.cpp.s:
	$(MAKE) -f CMakeFiles/NGA.dir/build.make CMakeFiles/NGA.dir/readNGA.cpp.s
.PHONY : readNGA.cpp.s

testMatrices.o: testMatrices.cpp.o
.PHONY : testMatrices.o

# target to build an object file
testMatrices.cpp.o:
	$(MAKE) -f CMakeFiles/TestsMatrix.dir/build.make CMakeFiles/TestsMatrix.dir/testMatrices.cpp.o
.PHONY : testMatrices.cpp.o

testMatrices.i: testMatrices.cpp.i
.PHONY : testMatrices.i

# target to preprocess a source file
testMatrices.cpp.i:
	$(MAKE) -f CMakeFiles/TestsMatrix.dir/build.make CMakeFiles/TestsMatrix.dir/testMatrices.cpp.i
.PHONY : testMatrices.cpp.i

testMatrices.s: testMatrices.cpp.s
.PHONY : testMatrices.s

# target to generate assembly for a file
testMatrices.cpp.s:
	$(MAKE) -f CMakeFiles/TestsMatrix.dir/build.make CMakeFiles/TestsMatrix.dir/testMatrices.cpp.s
.PHONY : testMatrices.cpp.s

testTaylor.o: testTaylor.cpp.o
.PHONY : testTaylor.o

# target to build an object file
testTaylor.cpp.o:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/testTaylor.cpp.o
.PHONY : testTaylor.cpp.o

testTaylor.i: testTaylor.cpp.i
.PHONY : testTaylor.i

# target to preprocess a source file
testTaylor.cpp.i:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/testTaylor.cpp.i
.PHONY : testTaylor.cpp.i

testTaylor.s: testTaylor.cpp.s
.PHONY : testTaylor.s

# target to generate assembly for a file
testTaylor.cpp.s:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/testTaylor.cpp.s
.PHONY : testTaylor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... AdamsIntegration"
	@echo "... GJIntegration"
	@echo "... NGA"
	@echo "... Tests"
	@echo "... TestsMatrix"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... TestAdams.o"
	@echo "... TestAdams.i"
	@echo "... TestAdams.s"
	@echo "... TestGJIntegrators.o"
	@echo "... TestGJIntegrators.i"
	@echo "... TestGJIntegrators.s"
	@echo "... readNGA.o"
	@echo "... readNGA.i"
	@echo "... readNGA.s"
	@echo "... testMatrices.o"
	@echo "... testMatrices.i"
	@echo "... testMatrices.s"
	@echo "... testTaylor.o"
	@echo "... testTaylor.i"
	@echo "... testTaylor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

